### PR TITLE
Docs 5967-PM Review

### PR DESCRIPTION
**Pull request by mcherem**
Docs for PM 3rd section review.

### CODE REVIEW

**Review by mcherem — COMMENTED** [review]
Reviewed these changes.

**Review by mcherem — COMMENTED** [review]
Reviewed changes.

**Review by mcherem — COMMENTED** [review]
Reviewed. Needs formatting fixes for MuleSoft style.

**Review by mcherem — COMMENTED** [review]
Formatting changes.

**Review by mcherem — COMMENTED** [review]
Needs formatting fixes. Approved with fixes.

**Review by mcherem — COMMENTED** [review]
Approved with formatting changes.

**Review by mcherem — COMMENTED** [review]
Formatting changes need to be made.

**Review by mcherem — COMMENTED** [review]
Approved and formatting fixes need to be made.

**Review by mcherem — COMMENTED** [review]
Approved with formatting changes.

**Review by amitfernandes — APPROVED** [review]
Approved

**Pull request merged**
